ignore_merge_commits = true
tag_prefix = "v"

pre_bump_hooks = ["sh -c \"echo '{{version}}' > NEXTVERSION\""]
post_bump_hooks = []

[commit_types]

[changelog]
path = "CHANGELOG.md"
authors = []
template = "remote"
remote = "github.com"
repository = "hyper-unix-socket"
owner = "kristof-mattei"

[bump_profiles]
